### PR TITLE
Test multiple python versions and improve travis conf

### PR DESCRIPTION
**Pull request by tusbar**

### CODE REVIEW

**Comment by tusbar** [comment]
@brmzkw ping

**Comment by tusbar** [comment]
``` python
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    version=get_version(),
  File "setup.py", line 28, in get_version
    res = re.match(r'^__version__ = [\'"](.*)[\'"]$', line)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/re.py", line 156, in match
    return _compile(pattern, flags).match(string)
TypeError: can't use a string pattern on a bytes-like object
```

**Comment by tusbar** [comment]
@brmzkw fix this now

**Comment by tusbar** [comment]
@evadot merge this now please

**Comment by evadot** [comment]
Merged, thanks !!!

**Pull request merged**
