### PR TITLE
Run millipede on Scaleway

### PR DESCRIPTION
**Pull request by edouardb**

### CODE REVIEW

**Comment by evadot** [comment]
Shouldn't we create another project for that ? like millipede-scw ? @tusbar ?

**Comment by edouardb** [comment]
I think we can keep it here at the moment as related to `millipede-python`.

**Comment by tusbar** [comment]
It could be fine here, or maybe in a scripts directory?

**Comment by edouardb** [comment]
Oh i know, `millipede-cloud` sound good

**Comment by evadot** [comment]
Perfect for me, @tusbar ?

**Comment by tusbar** [comment]
ok ;) with scripts to deploy it everywhere

**Comment by evadot** [comment]
Repository created, please re-do your PR on it.

**Pull request closed without merging**
