### PR TITLE
Added templates to customize your milipede

### PR DESCRIPTION
**Pull request by edouardb**

### CODE REVIEW

**Comment by tusbar** [comment]
Rebase from master & squash those commits together. :)

**Comment by evadot** [comment]
The branch cannot be merge.

And shouldn't body and bodyr be swapped ?

**Comment by edouardb** [comment]
Fixed.

**Comment by tusbar** [comment]
@evadot what do you mean swapped?

**Comment by evadot** [comment]
template['body'] is used if in reverse move and template['bodyr'] in normal mode.
For me bodyr means body-reverse.

**Comment by edouardb** [comment]
Done!

**Pull request merged**
