### PR TITLE
It's mille-pattes according to wikipedia

### PR DESCRIPTION
**Pull request by rockyluke**

### CODE REVIEW

**Comment by evadot** [comment]
I'll let the community chose if we change the text or not because my opinion is biased

**Comment by rockyluke** [comment]
o/

**Comment by tusbar** [comment]
:+1: 

then maybe reopen https://github.com/evadot/millipede/pull/8 :)

**Comment by rockyluke** [comment]
I think you're right, first time it was 'millepatte'.

**Comment by tusbar** [comment]
We should all be happy now that the French Academy recommends “millepatte” instead of “mille-pattes”… :)

**Pull request closed without merging**
